services:
    app:
        container_name: exam-timetable-bot
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        env_file: .env
        volumes:
            - ./src/:/home/app/src
